repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: black
      - id: check-yaml
      - id: end-of-file-fixer
      - id: isort
      - id: trailing-whitespace
