name: testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"

    - uses: snok/install-poetry@v1

    - name: dependencies
      run: |
        poetry install

    - name: testing with coverage
      run: |
        pytest --cov=saferequests --cov-report=xml tests/
      env:
        COVERAGE_FILE: ${{ runner.workspace }}/coverage.xml

    - name: coverage report to codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        file: ${{ runner.workspace }}/coverage.xml
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

    - name: coverage satisfaction
      run: |
        coverage=$(bash <(curl -s https://codecov.io/bash) -q -f ${{ runner.workspace }}/coverage.xml | grep "unit tests" | awk '{print $4}' | tr -d '%')

        if [ "$coverage" -lt 95 ]; then
            echo "coverage is below 95% ($coverage%)"
            exit 1
        fi
