name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .

    - name: Run tests with coverage
      run: |
        pytest --cov=proxyrotator tests/
      env:
        COVERAGE_FILE: ${{ runner.workspace }}/coverage.xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        file: ${{ runner.workspace }}/coverage.xml
        flags: unittests

    - name: Check coverage
      run: |
        COVERAGE=$(bash <(curl -s https://codecov.io/bash) -q -f ${{ runner.workspace }}/coverage.xml | grep "unit tests" | awk '{print $4}' | tr -d '%')
        if [ "$COVERAGE" -lt 95 ]; then
          echo "Error: Coverage is below 95% ($COVERAGE%)."
          exit 1
        fi
